---
title: "Hartford CT"
author: "Ruoqi Zhang"
date: "3/26/2019"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(socviz)
library(tidyverse)
library(maps)
library(ggmap)
library(fs)
library(gt)
```

```{r data_proc, echo=FALSE, cache=TRUE}
download.file(url = "https://stacks.stanford.edu/file/druid:tr137st9964/tr137st9964_ct_hartford_2019_02_25.rds",
              destfile = "ct_hartford.rds",
              mode = "wb")

hartford <- read_rds("ct_hartford.rds")

#Then, we delete the file so it doesn't interfere with further processes
file_delete("ct_hartford.rds")
```

```{r, echo=FALSE}
hartford %>% select(district, reason_for_stop) %>% group_by(reason_for_stop) %>% summarize(total = n()) %>% ggplot(aes(x = reason_for_stop, y = total)) + geom_col() +
  #facet_wrap(~district) 
  coord_flip()
```

```{r, echo=FALSE}
hartford %>% select(district, subject_race) %>% group_by(subject_race) %>% summarize(total = n()) %>% ggplot(aes(x = subject_race, y = total)) + geom_col() +
  #facet_wrap(~district) 
  coord_flip()

```

```{r, echo=FALSE}
hartford %>% 
  filter(arrest_made == TRUE) %>% 
  select(district, subject_race) %>% 
  count(district, subject_race) %>% 
  filter(!is.na(district)) %>% 
  spread(key = subject_race, value = n, fill = 0) %>% 
  mutate(total = `asian/pacific islander` + `black` + `hispanic` + `white`) %>% 
  arrange(desc(total)) %>% 
  gt() %>% 
  tab_header(
    title = "Number of Arrests Made in Hartford by Race"
  ) %>% 
  cols_label(
    district = "District",
    black = "Black",
    hispanic = "Hispanic",
    white = "White",
    `asian/pacific islander` = "Asian/Pacific Islanders"
  ) %>% 
  tab_source_note(
    source_note = "Source: The Stanford Open Policing Project"
  )
  
```

